server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?&serverTimezone = UTC&useSSL=false
    username: root
    password: 961214

mybatis:
  mapper-locations: classpath*:mapper/*.xml
